### ISSUE TITLE
third-party updates breaks Friction

### ISSUE THREAD

**Issue by rodlie** [friction2d/skia#1]
Latest update of third-party libs breaks static linking in Friction on Linux (not tested on Windows).

Find out what and why.

This is a blocker for Friction v1.0.0-beta.1

**Comment by eFe-Munoz** [comment]
Is it necessary to test the gon on Windows?

**Comment by rodlie** [comment]
Not needed, but thanks for asking.

I will fix this locally and push an update when it works (the public builds are ok, I reverted the changes).

**Comment by eFe-Munoz** [comment]
When proposals and bug reports can be made, let me know.

**Comment by rodlie** [comment]
Just add issues whenever you feel like it.

**Comment by eFe-Munoz** [comment]
ok

**Comment by kaixoo** [comment]
Can you add more details as to what exactly is failing? Is it a problem upstream, something to do with Friction itself...?

**Comment by rodlie** [comment]
I updated third-party libs in skia, this segfault Friction. Probably related to libwebp (or expat), will fix this before release.

**Comment by eFe-Munoz** [comment]
Good news. Any advance of when the official version will be ready?
